password:
  ssl: "wanglin.1"
yi:
  redis:
    host: 192.168.88.47
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 1
  jwt:
    secretKey: abb328128
    ttl: 7200000
    tokenName: Authorization
  wechat:
    appid: wx6354d27fc936c703
    secret: 77cec7b733043017dbc9c02fc4ea9e11